services:
  - type: web
    name: breakout-run-api
    runtime: python
    plan: starter
    buildCommand: pip install -r backend/requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: ALPHA_VANTAGE_API_KEY
        value: SPV6KJ86E42SSV0R
      - key: BRAVE_API_KEY
        value: BSARPt4icZph_z4Ma53e-iNv60qrLJX
      - key: PYTHON_VERSION
        value: 3.11.0
    healthCheckPath: /health
    autoDeploy: true
